version: '3'

services:
  dashbuilder-runtime:
    build: ./dashbuilder-runtime-dev
    environment:
      - JAVA_OPTS=$JAVA_OPTS -Ddashbuilder.runtime.multi=true -Ddashbuilder.components.dir=/tmp/runtime/components -Ddashbuilder.components.enable=true -Ddashbuilder.dataset.partition=false -Ddashbuilder.dev=true
    volumes:
      - ./models:/tmp/dashbuilder/models:z
    ports: 
     - 8080:8080
